name: HB1Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8057612092234194
  lightness: 0.022768122609704733
  saturation: 0.6947083824779838
  rhythmicContrast: 0.4860063164960593
purpose: []
